name: Python Tests

on: 
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name:
    #   uses: 
    #   with:

    # - name:
    #   run: 
